trigger:
 - master


pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK 7.0.032'
    inputs:
      version: '7.0.302'
      includePreviewVersions: true

  - script: dotnet publish
    displayName: 'Publish .NET Core project'

  
  - task: Docker@2
    inputs:
      containerRegistry: 'example'
      repository: 'testgathrr'
      command: 'push'
